---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: openshift-v4.13.22
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.13.22-x86_64
---
apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  name: openshift-v4.14.2
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:4.14.2-x86_64

