apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: sno-worker01
  namespace: edwin-home
spec:
  baseDomain: edwin.home
  clusterName: sno-worker01
  controlPlaneConfig:
    servingCertificates: {}
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: sno-worker01
    version: v1beta1
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          cluster-name: "sno-worker01"
  pullSecretRef:
    name: pull-secret