apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: sno-worker01
  namespace: sno-worker01
  labels:
    cluster-name: sno-worker01
spec:
  config:
    interfaces:
      - name: enp1s0
        type: ethernet
        state: up
        mac-address: '52:54:00:49:ba:ed'
        ipv4:
          enabled: true
          address:
            - ip: 192.168.31.101
              prefix-length: 24
          dhcp: false          
        ipv6:
          enabled: false   
    dns-resolver:
      config:
        server:
          - 192.168.31.10
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 192.168.31.1
          next-hop-interface: enp1s0
          table-id: 254
  interfaces:
    - name: "enp1s0"
      macAddress: '52:54:00:49:ba:ed'