apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: edwin-home
  namespace: edwin-home
  labels:
    agentclusterinstalls.extensions.hive.openshift.io/location: home
    networkType: static
spec:
  agentLabels:
    agentclusterinstalls.extensions.hive.openshift.io/location: home
  cpuArchitecture: x86_64
  ipxeScriptType: DiscoveryImageAlways
  nmStateConfigLabelSelector:
    matchLabels:
      edwin-home-nmstate-label: sno-worker1
  pullSecretRef:
    name: pullsecret-edwin-home