apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: mynmstateconfig
  namespace: sno-worker1
  labels:
    edwin-home-nmstate-label: sno-worker1
spec:
  config:
    interfaces:
      - name: enp1s0
        type: ethernet
        state: up
        #mac-address: 02:00:00:80:12:14
        ipv4:
          enabled: true
          address:
            - ip: 192.168.31.220
              prefix-length: 24
          dhcp: false      
    dns-resolver:
      config:
        server:
          - 192.168.31.10
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 192.168.31.1
          next-hop-interface: enp1s0
          table-id: 254
  interfaces:
    - name: "enp1s0"
      macAddress: "02:00:00:80:12:14"   
